-- Insert Finnish names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Aino', 'Virtanen', 'finnish'),
('Eero', 'Korhonen', 'finnish'),
('Tuuli', 'Mäkinen', 'finnish'),
('Mikko', 'Nieminen', 'finnish'),
('Liisa', 'Hämäläinen', 'finnish'),
('Jukka', 'Laine', 'finnish'),
('Sanna', 'Heikkinen', 'finnish'),
('Antti', 'Koskinen', 'finnish'),
('Kaisa', 'Järvinen', 'finnish'),
('Matti', 'Lehtonen', 'finnish'),
('Emilia', 'Mäkelä', 'finnish'),
('Lauri', 'Saarinen', 'finnish'),
('Sofia', 'Heinonen', 'finnish'),
('Oskari', 'Niskanen', 'finnish'),
('Helmi', 'Kinnunen', 'finnish'),
('Aleksi', 'Leppänen', 'finnish'),
('Venla', 'Rantanen', 'finnish'),
('Ville', 'Salonen', 'finnish'),
('Aada', 'Tuominen', 'finnish'),
('Eetu', 'Tamminen', 'finnish');

-- Insert Swedish names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Astrid', 'Andersson', 'swedish'),
('Erik', 'Johansson', 'swedish'),
('Ingrid', 'Karlsson', 'swedish'),
('Lars', 'Nilsson', 'swedish'),
('Saga', 'Eriksson', 'swedish'),
('Gustav', 'Larsson', 'swedish'),
('Elsa', 'Olsson', 'swedish'),
('Magnus', 'Persson', 'swedish'),
('Freja', 'Svensson', 'swedish'),
('Bjorn', 'Gustafsson', 'swedish'),
('Linnea', 'Pettersson', 'swedish'),
('Anders', 'Jonsson', 'swedish'),
('Maja', 'Jansson', 'swedish'),
('Viktor', 'Hansson', 'swedish'),
('Elin', 'Bengtsson', 'swedish'),
('Oskar', 'Lundgren', 'swedish'),
('Nova', 'Lindberg', 'swedish'),
('Felix', 'Jakobsson', 'swedish'),
('Alma', 'Axelsson', 'swedish'),
('Emil', 'Bergström', 'swedish');

-- Insert Norwegian names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Ingrid', 'Hansen', 'norwegian'),
('Ole', 'Johansen', 'norwegian'),
('Solveig', 'Olsen', 'norwegian'),
('Bjørn', 'Larsen', 'norwegian'),
('Kari', 'Andersen', 'norwegian'),
('Tor', 'Pedersen', 'norwegian'),
('Sigrid', 'Nilsen', 'norwegian'),
('Arne', 'Kristiansen', 'norwegian'),
('Liv', 'Jensen', 'norwegian'),
('Magnus', 'Karlsen', 'norwegian'),
('Emma', 'Johnsen', 'norwegian'),
('Henrik', 'Pettersen', 'norwegian'),
('Nora', 'Eriksen', 'norwegian'),
('Lars', 'Moen', 'norwegian'),
('Ingeborg', 'Berg', 'norwegian'),
('Eirik', 'Haugen', 'norwegian'),
('Astrid', 'Bakke', 'norwegian'),
('Håkon', 'Strand', 'norwegian'),
('Thea', 'Sørensen', 'norwegian'),
('Kristian', 'Dahl', 'norwegian');

-- Insert Danish names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Freja', 'Nielsen', 'danish'),
('Mads', 'Jensen', 'danish'),
('Emma', 'Hansen', 'danish'),
('Rasmus', 'Pedersen', 'danish'),
('Ida', 'Andersen', 'danish'),
('Kasper', 'Christensen', 'danish'),
('Sofia', 'Larsen', 'danish'),
('Frederik', 'Sørensen', 'danish'),
('Isabella', 'Rasmussen', 'danish'),
('Mikkel', 'Jørgensen', 'danish'),
('Clara', 'Petersen', 'danish'),
('Christian', 'Madsen', 'danish'),
('Laura', 'Mortensen', 'danish'),
('Nikolaj', 'Thomsen', 'danish'),
('Alma', 'Christiansen', 'danish'),
('Magnus', 'Poulsen', 'danish'),
('Ella', 'Johansen', 'danish'),
('Anders', 'Knudsen', 'danish'),
('Anna', 'Olsen', 'danish'),
('Lasse', 'Kristensen', 'danish');

-- Insert Irish names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Aoife', 'Murphy', 'irish'),
('Liam', 'Kelly', 'irish'),
('Saoirse', 'O''Sullivan', 'irish'),
('Conor', 'Walsh', 'irish'),
('Niamh', 'O''Brien', 'irish'),
('Sean', 'Ryan', 'irish'),
('Ciara', 'McCarthy', 'irish'),
('Patrick', 'O''Connor', 'irish'),
('Aisling', 'Byrne', 'irish'),
('Cian', 'Doyle', 'irish'),
('Caoimhe', 'Brennan', 'irish'),
('Eoin', 'Duffy', 'irish'),
('Siobhan', 'Kennedy', 'irish'),
('Ronan', 'Lynch', 'irish'),
('Maeve', 'Murray', 'irish'),
('Tadhg', 'Quinn', 'irish'),
('Roisin', 'Moore', 'irish'),
('Oisin', 'McLaughlin', 'irish'),
('Orla', 'Carroll', 'irish'),
('Darragh', 'Gallagher', 'irish');

-- Insert Scottish names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Ailsa', 'MacDonald', 'scottish'),
('Angus', 'Campbell', 'scottish'),
('Fiona', 'Stewart', 'scottish'),
('Hamish', 'Robertson', 'scottish'),
('Moira', 'Thomson', 'scottish'),
('Callum', 'Anderson', 'scottish'),
('Isla', 'Scott', 'scottish'),
('Duncan', 'Murray', 'scottish'),
('Eilidh', 'Reid', 'scottish'),
('Fraser', 'Wilson', 'scottish'),
('Catriona', 'MacLeod', 'scottish'),
('Ewan', 'Cameron', 'scottish'),
('Mairead', 'Fraser', 'scottish'),
('Iain', 'MacKenzie', 'scottish'),
('Elspeth', 'Grant', 'scottish'),
('Gregor', 'Ferguson', 'scottish'),
('Kirsty', 'Graham', 'scottish'),
('Rory', 'Ross', 'scottish'),
('Morven', 'Johnston', 'scottish'),
('Alistair', 'Kennedy', 'scottish');

-- Insert Welsh names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Rhiannon', 'Jones', 'welsh'),
('Gareth', 'Williams', 'welsh'),
('Bronwen', 'Davies', 'welsh'),
('Dylan', 'Evans', 'welsh'),
('Cerys', 'Thomas', 'welsh'),
('Owain', 'Roberts', 'welsh'),
('Gwen', 'Lewis', 'welsh'),
('Idris', 'Hughes', 'welsh'),
('Eira', 'Morgan', 'welsh'),
('Rhys', 'Griffiths', 'welsh'),
('Carys', 'Edwards', 'welsh'),
('Gethin', 'Jenkins', 'welsh'),
('Angharad', 'Price', 'welsh'),
('Iolo', 'Rees', 'welsh'),
('Megan', 'Phillips', 'welsh'),
('Dewi', 'Lloyd', 'welsh'),
('Sian', 'Owen', 'welsh'),
('Dafydd', 'Parry', 'welsh'),
('Bethan', 'Richards', 'welsh'),
('Huw', 'Morris', 'welsh');

-- Insert Dutch names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Emma', 'de Jong', 'dutch'),
('Daan', 'Jansen', 'dutch'),
('Sophie', 'de Vries', 'dutch'),
('Lucas', 'van den Berg', 'dutch'),
('Julia', 'van Dijk', 'dutch'),
('Sem', 'Bakker', 'dutch'),
('Anna', 'Visser', 'dutch'),
('Luuk', 'Smit', 'dutch'),
('Eva', 'Meijer', 'dutch'),
('Bram', 'de Boer', 'dutch'),
('Lotte', 'Mulder', 'dutch'),
('Lars', 'de Groot', 'dutch'),
('Fleur', 'Bos', 'dutch'),
('Thijs', 'Vos', 'dutch'),
('Saar', 'Peters', 'dutch'),
('Stijn', 'Hendriks', 'dutch'),
('Noor', 'van Leeuwen', 'dutch'),
('Jasper', 'Dekker', 'dutch'),
('Lisa', 'Brouwer', 'dutch'),
('Milan', 'de Wit', 'dutch');

-- Insert German names
INSERT INTO public.names (first_name, last_name, region) VALUES
('Hannah', 'Müller', 'german'),
('Lukas', 'Schmidt', 'german'),
('Emma', 'Schneider', 'german'),
('Leon', 'Fischer', 'german'),
('Mia', 'Weber', 'german'),
('Felix', 'Meyer', 'german'),
('Sophia', 'Wagner', 'german'),
('Paul', 'Becker', 'german'),
('Anna', 'Schulz', 'german'),
('Jonas', 'Hoffmann', 'german'),
('Lena', 'Koch', 'german'),
('Maximilian', 'Richter', 'german'),
('Laura', 'Klein', 'german'),
('Elias', 'Wolf', 'german'),
('Marie', 'Schröder', 'german'),
('Noah', 'Neumann', 'german'),
('Lea', 'Schwarz', 'german'),
('Ben', 'Zimmermann', 'german'),
('Sarah', 'Braun', 'german'),
('Tim', 'Hofmann', 'german');